language: python
install:
    - pip install flask

python:
    - "2.7"
    - "pypy"
    - "3.4"
    - "3.5"

script:
    - nosetests -s

after_success:
    - pip install coveralls
    - coverage run --source=flask_shorturl setup.py -q nosetests
    - coveralls

notifications:
    email: false
